### ISSUE TITLE
README_ANSIBLE.md contains internal link

### ISSUE THREAD

**Issue by myounker** [ciscops/viptela-workshop#1]
Cloning this repo:

_git clone https://wwwin-github.cisco.com/ciscops/virl-viptela.git

**Comment by stevenca** [comment]
Which file was this in?  I see:

# Exercise 1.0 -  Using Ansible with Viptela SDx Workshop
## Step1
Cloning the workshop repo repo:
git clone `https://github.com/ciscops/viptela-workshop.git`
