### ISSUE TITLE
Exercise 4.1 Changes to enable NETCONF

### ISSUE THREAD

**Issue by tovail** [ciscops/viptela-workshop#11]
---
- name: CONFIGURE ROUTERS
  hosts: routers
  connection: netconf
  gather_facts: no
  tasks:
    - name: ENABLE NETCONF/YANG
      ios_config:
        commands:
          - netconf-yang
      connection: network_cli

    - name: ENSURE THAT THE DESIRED NTP SERVERS ARE PRESENT
      netconf_rpc:
        rpc: edit-config
        content: |
          <target>
            <running/>
          </target>
          <config>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <ntp>
                <server xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ntp" operation='replace'>
                  <server-list>
                    <ip-address>192.5.41.40</ip-address>
                  </server-list>
                  <server-list>
                    <ip-address>192.5.41.41</ip-address>
                  </server-list>
                </server>
              </ntp>
            </native>
          </config>

**Comment by stevenca** [comment]
Addressed.  Will add specific PR#.
