### ISSUE TITLE
Exercise 6.1 - step 1

### ISSUE THREAD

**Issue by alexct451** [ciscops/viptela-workshop#14]
For the following:

- debug:
        msg: "{{ existing_ntp_servers | difference(ntp_servers) }}"

existing_ntp_servers should be changed to actual_ntp_servers

**Comment by alexct451** [comment]
Also this line should be changed:
$ ansible-playbook textfsm.yml --limit=core

to 

$ ansible-playbook textfsm2.yml --limit=core

**Comment by stevenca** [comment]
Addressed.  Will update with specific PR#
